export default async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
 const q=String(req.body?.query||'').trim();
 if(!q)return res.status(400).json({error:'Query required'});
 if(!process.env.PARALLEL_API_KEY)return res.status(503).json({error:'Live search provider credential is not configured on the server'});
 const prompt=researchPrompt(q);
 try{
  const r=await fetch('https://api.parallel.ai/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${process.env.PARALLEL_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:'parallel',input:prompt,reasoning:{effort:'medium'},text:{format:{type:'json_schema',name:'care_wisdom_research',schema:{type:'object',properties:{question:{type:'string'},research_branches:{type:'array',items:{type:'object',properties:{name:{type:'string'},why:{type:'string'}},required:['name','why'],additionalProperties:false}},overview:{type:'string'},patterns:{type:'array',items:{type:'object',properties:{title:{type:'string'},category:{type:'string',enum:['lived_experience','clinical_context','mixed']},what_people_reported:{type:'string'},evidence_check:{type:'string'},disagreement:{type:'string'},independence_note:{type:'string'},care_team_questions:{type:'array',items:{type:'string'}},source_titles:{type:'array',items:{type:'string'}}},required:['title','category','what_people_reported','evidence_check','disagreement','independence_note','care_team_questions','source_titles'],additionalProperties:false}},sources:{type:'array',items:{type:'object',properties:{title:{type:'string'},url:{type:'string'},type:{type:'string',enum:['community','patient_org','clinical','journalism','other']},domain:{type:'string'}},required:['title','url','type','domain'],additionalProperties:false}},limitations:{type:'array',items:{type:'string'}},safety_flags:{type:'array',items:{type:'string'}}},required:['question','research_branches','overview','patterns','sources','limitations','safety_flags'],additionalProperties:false}}}} )});
  const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{return res.status(502).json({error:'Research provider returned a non-JSON response',detail:raw.slice(0,500)})}
  if(!r.ok)return res.status(502).json({error:'Research provider error',detail:data?.error?.message||data?.message||'Provider rejected the request'});
  const text=outputText(data);let result;try{result=JSON.parse(text.replace(/^\s*```json\s*/,'').replace(/\s*```\s*$/,''))}catch{return res.status(502).json({error:'Research synthesis was not valid JSON',detail:text.slice(0,1000)})}
  const citations=getCitations(data);result.sources=normalizeSources([...(result.sources||[]),...citations]);
  const domains=[...new Set(result.sources.map(s=>domainOf(s.url)).filter(Boolean))];
  return res.status(200).json({...result,source_stats:{total:result.sources.length,independent_domains:domains.length,lived_experience_sources:result.sources.filter(s=>s.type==='community').length,domains}});
 }catch(e){return res.status(500).json({error:'Research failed',detail:String(e).slice(0,500)})}
}
function researchPrompt(q){return `You are Care Wisdom's deep-research engine. User question: "${q.replace(/"/g,'\\\"')}"
Do a source-diverse, multi-step web investigation. Decompose the question into 5-8 research branches appropriate to the actual problem. Seek independent caregiver/patient/community discussions, patient/family organizations, peer-reviewed/government/academic medical sources, and high-quality journalism when useful. Do not pad results with generic pages or many pages from one site.
Synthesize only genuine recurring patterns. A pattern is an underlying practical issue supported by multiple relevant reports or by strong clinical context—not a source title. Distinguish independent reports from multiple pages on one domain. Compare lived experience with clinical evidence. Preserve disagreement and uncertainty. Do not diagnose, prescribe, rank treatments, or turn anecdotes into instructions. Generate 2-4 concrete questions for the appropriate care team for each pattern.
Prefer 12-25 genuinely useful sources when the evidence supports it. If evidence is thin, say so.
Return ONLY valid JSON:
{"question":string,"research_branches":[{"name":string,"why":string}],"overview":string,"patterns":[{"title":string,"category":"lived_experience|clinical_context|mixed","what_people_reported":string,"evidence_check":string,"disagreement":string,"independence_note":string,"care_team_questions":[string],"source_titles":[string]}],"sources":[{"title":string,"url":string,"type":"community|patient_org|clinical|journalism|other","domain":string}],"limitations":[string],"safety_flags":[string]}
Use only sources actually researched; never invent URLs or citations.`;}
function outputText(data){if(data.output_text)return data.output_text;for(const item of(data.output||[]))for(const p of(item.content||[]))if(p.type==='output_text'&&p.text)return p.text;return '';}
function getCitations(data){const a=[];for(const item of(data.output||[]))for(const p of(item.content||[]))for(const x of(p.annotations||[]))if(x.type==='url_citation'&&x.url)a.push({title:x.title||x.url,url:x.url,type:guessType(x.url,x.title||'')});return a;}
function normalizeSources(items){const seen=new Set(),out=[];for(const s of items){const url=canonical(s.url||'');if(!url||seen.has(url))continue;seen.add(url);out.push({title:s.title||url,url,type:['community','patient_org','clinical','journalism','other'].includes(s.type)?s.type:guessType(url,s.title||''),domain:domainOf(url)});}return out.slice(0,30);}
function domainOf(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return ''}}
function canonical(u){try{const x=new URL(u);['utm_source','utm_medium','utm_campaign','utm_term','utm_content','fbclid','gclid','mc_cid','mc_eid'].forEach(k=>x.searchParams.delete(k));x.hash='';return x.origin+x.pathname.replace(/\/$/,'')}catch{return ''}}
function guessType(url,title){const h=(url+' '+title).toLowerCase();if(/reddit|agingcare|forum|community|discussion/.test(h))return 'community';if(/parkinson\.org|lbda|movementdisorders\.org/.test(h))return 'patient_org';if(/pubmed|nih\.gov|ncbi\.nlm|mayoclinic|hopkinsmedicine|stanford\.edu|neuropt\.org|apta\.org|\.edu\//.test(h))return 'clinical';if(/reuters|nytimes|washingtonpost|aarp|statnews|npr\.org/.test(h))return 'journalism';return 'other';}
